export const FoodMenu = [
  {
    category: "Roti/Naan",
    items: [
      { id: 112, name: "Double Roti", price: 15 },
      { id: 113, name: "Butter Roti", price: 20 },
      { id: 114, name: "Missi Roti", price: 30 },
      { id: 115, name: "Green Chilli Paratha", price: 30 },
      { id: 116, name: "Lachcha Paratha", price: 40 },
      { id: 117, name: "Butter Naan", price: 60 },
    ],
  },
  {
    category: "Tikka",
    items: [
      { id: 120, name: "Mushroom Tikka", price: 310 },
      { id: 121, name: "Mushroom Achari Tikka", price: 320 },
      { id: 122, name: "Mushroom Malai Tikka", price: 330 },
      { id: 123, name: "Paneer Achari Tikka", price: 340 },
      { id: 124, name: "Paneer Tikka", price: 350 },
      { id: 125, name: "Paneer Malai Tikka", price: 350 },
      { id: 126, name: "Paneer Afgani Tikka", price: 380 },
    ],
  },
  {
    category: "Desserts",
    items: [
      { id: 127, name: "Hot Gulab Jamun (1 Pc.)", price: 20 },
      { id: 128, name: "Vanilla", price: 30 },
      { id: 129, name: "Strawberry", price: 30 },
      { id: 130, name: "Butter Scotch", price: 40 },
      { id: 131, name: "Mix Fruit", price: 50 },
    ],
  },
  {
    category: "Salad/Raita",
    items: [
      { id: 5, name: "Onion Salad", price: 70 },
      { id: 6, name: "Hara Bhara Taja Salad", price: 80 },
      { id: 67, name: "Cucumber Salad", price: 80 },
      { id: 68, name: "Raisin Salad", price: 90 },
      { id: 69, name: "Cream Cucumber Salad", price: 100 },
      { id: 70, name: "Plain Raita", price: 90 },
      { id: 71, name: "Boondi Raita", price: 100 },
      { id: 72, name: "Aloo Mint Raita", price: 100 },
      { id: 73, name: "Mix Raita", price: 110 },
      { id: 74, name: "Cucumber Raita", price: 110 },
    ],
  },
  {
    category: "Rice",
    items: [
      { id: 75, name: "Steam Rice", price: 100 },
      { id: 76, name: "Zeera Rice", price: 110 },
      { id: 77, name: "Mutter Pulao", price: 170 },
      { id: 78, name: "Veg. Pulao", price: 180 },
      { id: 79, name: "Veg. Fried Rice", price: 180 },
      { id: 80, name: "Veg. Biryani", price: 220 },
    ],
  },
  {
    category: "Pasta",
    items: [
      { id: 81, name: "Veg. Pasta", price: 100 },
      { id: 82, name: "Red Pasta", price: 120 },
      { id: 83, name: "White Pasta", price: 130 },
    ],
  },
  {
    category: "Main Course",
    items: [
      { id: 84, name: "Kad Pakoda", price: 170 },
      { id: 85, name: "Zeera Aloo", price: 180 },
      { id: 86, name: "Rasila Rajma", price: 180 },
      { id: 87, name: "Rajma Masala", price: 190 },
      { id: 88, name: "Mix Veg.", price: 190 },
      { id: 89, name: "Yellow Dal Tadka", price: 200 },
      { id: 90, name: "Black Dal Tadka", price: 210 },
      { id: 91, name: "Kadhai Vegetable", price: 210 },
      { id: 92, name: "Dal Makhni", price: 240 },
      { id: 93, name: "Dal Bukhara", price: 250 },
      { id: 94, name: "Chana Paneer", price: 280 },
      { id: 95, name: "Mushroom Mutter", price: 280 },
      { id: 96, name: "Mushroom Do Pyaza", price: 280 },
      { id: 97, name: "Mushroom Masala", price: 280 },
      { id: 98, name: "Malai Kofta (Red)", price: 290 },
      { id: 99, name: "Malai Kofta (White)", price: 290 },
      { id: 100, name: "Cheese Tomato", price: 300 },
      { id: 101, name: "Paneer Taka Tak", price: 300 },
      { id: 102, name: "Paneer Lababdar", price: 300 },
      { id: 103, name: "Kadhai Paneer", price: 300 },
      { id: 104, name: "Shahi Paneer", price: 310 },
      { id: 105, name: "Paneer Masala", price: 310 },
      { id: 106, name: "Paneer Do Pyaza", price: 310 },
      { id: 107, name: "Paneer Bhurji", price: 310 },
      { id: 108, name: "Paneer Makhani", price: 320 },
      { id: 109, name: "Paneer Butter Masala", price: 320 },
      { id: 110, name: "Paneer Tikka Butter Masala", price: 340 },
      { id: 111, name: "Saag (Seasonal)", price: "App." },
    ],
  },
  {
    category: "Snacks",
    items: [
      { id: 45, name: "Roasted Papad (1 Pc)", price: 10 },
      { id: 46, name: "Masala Papad (2 Pcs)", price: 40 },
      { id: 47, name: "Chana Chat", price: 60 },
      { id: 48, name: "Roasted Peanut", price: 100 },
      { id: 49, name: "Peanut Masala", price: 150 },
      { id: 50, name: "Veg Noodles", price: 160 },
      { id: 51, name: "Veg Spring Roll", price: 160 },
      { id: 52, name: "Veg Manchurian (Dry)", price: 170 },
      { id: 53, name: "Chilli Garlic Noodles", price: 170 },
      { id: 54, name: "Veg Manchurian (Gravy)", price: 180 },
      { id: 55, name: "Hakka Noodles", price: 190 },
      { id: 56, name: "Cheese Spl. Noodles", price: 210 },
      { id: 57, name: "Mushroom Chilli (Dry)", price: 250 },
      { id: 58, name: "Mushroom Chilli (Gravy)", price: 260 },
      { id: 59, name: "Cheese Corn Roll", price: 260 },
      { id: 60, name: "Cottage Cheese Ginger Garlic", price: 290 },
      { id: 61, name: "Cottage Cheese Lemon (Gravy)", price: 300 },
      { id: 62, name: "Cheese Chilli (Dry)", price: 300 },
      { id: 63, name: "Cheese Chilli (Gravy)", price: 310 },
      { id: 64, name: "Paneer Singhapuri", price: 330 },
    ],
  },
  {
    category: "Beverages",
    items: [
      { id: 25, name: "Spl. Tea", price: 30 },
      { id: 26, name: "Milk Tea", price: 40 },
      { id: 27, name: "Black Tea", price: 25 },
      { id: 28, name: "Lemon Tea", price: 25 },
      { id: 29, name: "Hot Coffee", price: 60 },
      { id: 30, name: "Black Coffee", price: 50 },
      { id: 31, name: "Cold Coffee", price: 100 },
      { id: 32, name: "Cold Coffee with Ice Cream", price: 120 },
      { id: 33, name: "Fresh Lemon Water (Salted, Sweet)", price: 40 },
      { id: 34, name: "Fresh Lemongrass Water", price: 30 },
      { id: 35, name: "Mineral Water", price: 20 },
      { id: 36, name: "Cold Drink", price: "MRP" },
      { id: 37, name: "Strawberry Shake", price: 120 },
      { id: 38, name: "Vanilla Milk Shake", price: 120 },
      { id: 39, name: "Butter Scotch Milk Shake", price: 130 },
    ],
  },
  {
    category: "Breakfast",
    items: [
      { id: 1, name: "Aloo Parantha", price: 70 },
      { id: 2, name: "Gobi Parantha", price: 70 },
      { id: 3, name: "Onion Parantha", price: 70 },
      { id: 4, name: "Mix Parantha", price: 80 },
      { id: 5, name: "Paneer Parantha", price: 100 },
      { id: 6, name: "Puri Bhaji (3 Pcs)", price: 140 },
      { id: 7, name: "Chana Puri (3 Pcs)", price: 160 },
      { id: 8, name: "Aloo Kulcha (Gravy)", price: 150 },
      { id: 9, name: "Paneer Kulcha (Gravy)", price: 200 },
      { id: 10, name: "Boiled Vegetable", price: 160 },
      { id: 11, name: "Butter Tikki (1 Pc)", price: 10 },
      { id: 12, name: "Butter Toast (4 Pcs)", price: 40 },
      { id: 13, name: "Veg Sandwich (4 Pcs)", price: 60 },
      { id: 14, name: "Grilled Sandwich", price: 110 },
      { id: 15, name: "Cheese Grilled Sandwich", price: 160 },
      { id: 16, name: "Lassi Sweet", price: 60 },
      { id: 17, name: "Lassi Salted", price: 50 },
      { id: 18, name: "Curd", price: 20 },
      { id: 19, name: "Steam Momos (10 Pcs)", price: 130 },
      { id: 20, name: "Fried Momos (10 Pcs)", price: 160 },
      { id: 21, name: "Chilli Momos (10 Pcs)", price: 180 },
      { id: 22, name: "Tandoori Momos", price: 200 },
      { id: 23, name: "Veg. Burger", price: 60 },
      { id: 24, name: "Noodles Burger", price: 70 },
    ],
  },
];
